export const ORDER_CREATED = 'ORDER_CREATED';
export const SELLER_REGISTERED = 'SELLER_REGISTERED';
export const COMMENT_CREATED = 'COMMENT_CREATED';
export const COMMENT_ANSWERED = 'COMMENT_ANSWERED';
export const PRODUCT_RATED = 'PRODUCT_RATED';